// mysite/src/pages/finance/budget/budget/viewflow.tsx
import React, { useEffect, useState } from 'react';
import { Avatar, Typography,Steps,Card, Divider, Modal, Button, Tag, Descriptions,Tabs  } from 'antd';
import './costom.css'
import { getflowinfo,flowact, getfileurlsbycontractids } from './service';
import { currentUser } from '@/services/ant-design-pro/api';
import { useModel } from 'umi';
import TextArea from 'antd/lib/input/TextArea';
import { set } from 'lodash';
import Filescard from '../../contract/filescard';
import { FlowStateEunm, ProjectStatesEnum } from '../config';
import Flow from './flow';
import Offlineagree from './offlineagree';
import Print from './print';
import Budgetdetail from './budgetdetail';
import ViewFlow from '../../Flowtemplate/viewflow';
const { TabPane } = Tabs;
// style
const row:React.CSSProperties = {
  display: 'flex',
  flexDirection: 'row',
  width: '100%'
}
const col:React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'center'
}
const label:React.CSSProperties = {
  color: 'gray'
}
const mask:React.CSSProperties = {
  position: 'absolute',
  top: 0,
  left: 0,
  width: '100%',
  height: '100%',
  background: 'linear-gradient(to bottom, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.5))',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  zIndex: 9999,
  color: 'white',
  fontSize: '20px',
  fontWeight: 'bold',
  
}
// data
const { Title } = Typography;

/**
 * state 参数对应项目的state
 * @param param0 
 * @returns 
 */
const Viewflow:React.FC<{thirdno?:any,onchange?:Function,state?:any,projectid?:any}> = ({thirdno,onchange,state=-1,projectid})=> {

  const [speech, setSpeech] = useState('')
  
  const { initialState } = useModel<any>('@@initialState');
  const { currentUser } = initialState;
  const [basic,setBasic]= useState<any>({})
  const [viewdata,setViewdata] = useState<any>({})
  const [statusCn,setStatusCn] = useState([])
  const [step,setStep] = useState(0)
  const [incomecontracts,setIncomecontracts]=useState('')
  const [expendcontracts,setExpendcontracts]=useState('')
  const Step = Steps.Step;
  const [printModal,setPrintModal]=useState(false)
  const [offlineModal,setOfflineModal] = useState(false)
  const [modal2, setModal2] = useState(false)
  const [urls, setUrls] = useState('')
  var [refresh,setRefresh]=useState(0)
  const [approve,setApprove]=useState(false)
  const[viewflowmodal,setViewflowmodal]=useState(false)
  const [reset,setReset]=useState(false)
  useEffect(()=>{
    getflowinfo({thirdNo:thirdno,projectid,state}).then((res:any)=>{
      
      if (res.errorMessage) {
        Modal.error({
          title: '报错',
          content: res.errorMessage,
        });
      } else {
      
        setBasic(res.basic)
        setViewdata(res.viewdata)
        setStatusCn(res.statusCn)
        setIncomecontracts(res.incomecontracts)
        setExpendcontracts(res.expendcontracts)
        
        if (res.viewdata) {
          // 判断当前审批人是否已经审过
          setStep(res.viewdata.step+1)
          var node = res.viewdata.approval[res.viewdata.step+1]
          var temp = false
          if (node.NodeStatus==2){
            temp=true
          }else{
            var inx = node.Items.Item.findIndex((item:any)=>item.ItemUserId==currentUser.wxuserid)
            if (node.Items.Item[inx] && node.Items.Item[inx].ItemStatus==2) temp=true
          }
          setApprove(temp)
        }
        setRefresh(++refresh)
      }
    })
    
  },[])
  type Flow = {
    offline?: number;
    act: string;
    thirdNo?:string
    fileurls?:string
    speech?:string
    // 不通知指定人员|分割
    notNotice?:string
    continuous?:number
  
  };
  const onOfflineAgree = ()=>{
    setOfflineModal(true)
    setBasic(basic)
  }
  const offlineAgree = (values:Flow)=>{

    values.act='offlineAgree'
    values.offline=0
    
    act(values)
  }

  
  const actReject = (flow:Flow)=>{
    Modal.confirm({
      title: '确定【 驳回】吗？',
      onOk() {
        act(flow)
      },
    });
  }
  const actAgree = (flow:Flow)=>{
    Modal.confirm({
      title: '确定【同意】吗？',
      onOk() {
        act(flow)
      },
    });
  }
  const actCancel = (flow:Flow)=>{
    Modal.confirm({
      title: '确定要【撤销】吗？',
      onOk() {
        act(flow)
      },
    });
  }
  const act = (flow:Flow)=>{
 
    if (!flow.thirdNo) flow.thirdNo = thirdno
    if (!flow.speech) flow.speech=speech

    flowact(flow).then((flowres:any)=>{
      if (flowres.errorMessage){
        Modal.error({
          title: '报错',
          content: flowres.errorMessage,
        });
      }else{
        Modal.info({title:'操作成功！'})
        if (flowres.data && flowres.data.touser&&flowres.data.touser.indexOf(currentUser.wxuserid)>-1){
          flow.notNotice = currentUser.wxuserid
          flow.continuous = 1;
          act(flow)
        }else{
          getflowinfo({thirdNo:thirdno,projectid,state}).then((res:any)=>{
       
            if (res.errorMessage) {
              Modal.error({
                title: '报错',
                content: res.errorMessage,
              });
            } else {
              setBasic(res.basic)
              setViewdata(res.viewdata)
              setStatusCn(res.statusCn)
              if (res.viewdata) {
                // 判断当前审批人是否已经审过
                setStep(res.viewdata.step+1)
                var node = res.viewdata.approval[res.viewdata.step+1]
                var temp = false
                if (node.NodeStatus==2){
                  temp=true
                }else{
                  var inx = node.Items.Item.findIndex((item:any)=>item.ItemUserId==currentUser.wxuserid)
                  if (node.Items.Item[inx] && node.Items.Item[inx].ItemStatus==2) temp=true
                }
                setApprove(temp)
              }
              

              if (onchange) onchange(res)
            }
          })
        }
        
      }
    })
    
  }
  var income = 0
  var expend = 0
  var profit = 0
  if (basic.finalincome>0){
    income = basic.finalincome
    expend = basic.realfinalexpend
  }else{
    income = basic.budgetincome
    expend = basic.realbudgetexpend
  }
  profit = income-expend
  profit = profit>0?profit:0
  return (
    <div key={refresh} style={{position:'relative'}}>
      {
        viewdata==0 &&
        <Card>
          请先提交审批
        </Card>
      }
      {
        viewdata!=0 &&
        <div >
           {

            ['已取消'].includes(statusCn[basic.status]) &&
            <div style={mask}>
              <div style={{color:'black',fontSize:'40px'}}>{statusCn[basic.status]}</div>
            </div>
           }
           {
            !['已取消'].includes(statusCn[basic.status]) && basic.reject==1 &&
            <div style={mask}>
              <div style={{color:'black',fontSize:'30px'}}>
                    <span style={{marginRight:'20px',color:'cadetblue',borderBottom:'2px solid cadetblue'}} onClick={() => {
                      
                      
                        Modal.confirm({
                          title: '确定要提交审批吗？',
                          onOk() {
                            act({act:'continue'})
                          },
                        });

                      }}>
                      提交审批
                    </span>
                    <span style={{color:'black',borderBottom:'2px solid black'}} onClick={() =>act({act:'cancel'})}>
                      撤销
                    </span>
              </div>
            </div>
           }
            {/* <Card   style={{ width: '100%' }}> */}
              {
                basic.userName &&
                <div>
                  <div style={{...row,alignItems:'center'}}>
                    <Avatar src={basic.avatar} size="large" />
                    <Title style={{height:'100%',display:'flex',alignItems:'center'}} level={4} >
                        {basic.userName+'的审批申请'}
                        {
                          basic.status!=FlowStateEunm.NONE && <Tag color="red">{statusCn[basic.status]}</Tag>
                        }
                        {
                          basic.state>=ProjectStatesEnum.START && (basic.typename||basic.statename)!='提交计量' && <Button style={{padding:'0 10px',height: '23px',fontSize: '12px'}} type='primary' onClick={()=>{
                          
                            setPrintModal(true)
                            setBasic(basic)
                          }}>打印</Button>
                        }
                      </Title>
                  </div>
                  <Divider></Divider>
                  <Descriptions
                      bordered
                      size={'small'}
                      column={2}
                      labelStyle={{width:120}}
                    >
                   
                      {
                        basic?.thirdNo&&
                        <Descriptions.Item label="审批单号"><span style={{color:"#1890FF"}} onClick={()=>{
                                setViewflowmodal(true)
                                
                            }}>{basic?.thirdNo}</span></Descriptions.Item>
                      }
                      <Descriptions.Item label="项目名称">{basic.title}</Descriptions.Item>
                      <Descriptions.Item label="项目类型">{basic?.protypename}</Descriptions.Item>
                      {
                        basic.submitdate!=null &&
                        <Descriptions.Item label="提交日期">{basic?.submitdate.substr(0,7)}</Descriptions.Item>
                      }
                      <Descriptions.Item label="申请类型">{basic.typename||basic.statename}{basic.statename&&basic.statename!=basic.typename&&basic.statename!='立项'?"（未"+basic.statename+"）":""}</Descriptions.Item>
                      <Descriptions.Item label="项目负责人">{basic.chargername}</Descriptions.Item>
                      <Descriptions.Item label="立项部门">{basic.pdepartment}</Descriptions.Item>
                      <Descriptions.Item label="立项主体">{basic.partbname}</Descriptions.Item>
                      <Descriptions.Item label="申请部门">{basic.department}</Descriptions.Item>
                      <Descriptions.Item label="总收入">{income.toLocaleString('en-US', {minimumFractionDigits: 2,maximumFractionDigits: 2,})}</Descriptions.Item>
                      <Descriptions.Item label="总支出">{expend.toLocaleString('en-US', {minimumFractionDigits: 2,maximumFractionDigits: 2,})}</Descriptions.Item>
                      <Descriptions.Item label="毛利润">{profit.toLocaleString('en-US', {minimumFractionDigits: 2,maximumFractionDigits: 2,})}</Descriptions.Item>
                      <Descriptions.Item label="合同状态">
                        {
                          basic.contractids && 
                          <a href='#' onClick={()=>{
                            getfileurlsbycontractids({contractids:basic.contractids}).then((res=>{
                              setUrls(res.data||'')
                              setModal2(true)
                            }))
                          }}>
                            已签
                          </a>
                        }
                        {
                          !basic.contractids && '未签'
                        }
                      </Descriptions.Item>
                      
                  </Descriptions>
 
                    <Descriptions
                      bordered
                      size={'small'}
                      column={1}
                      labelStyle={{width:120}}
                    >
                     {
                        basic.content &&basic.content!='' &&
                        <Descriptions.Item label="项目备注">{basic.content}</Descriptions.Item>
                      }
                      {
                        basic.fileurls &&
                        <Descriptions.Item label="预算附件">
                          <Filescard key={basic.id} mode='list' urls={basic.fileurls}/>
                        </Descriptions.Item>
                      }
                      {
                        basic.finalfileurls &&
                        <Descriptions.Item label="决算附件">
                          <Filescard key={basic.id} mode='list' urls={basic.finalfileurls}/>
                        </Descriptions.Item>
                      }
                    </Descriptions>
                    
                </div>
              }
              
              

              
            {/* </Card> */}


            <Flow data={viewdata} condition={basic} statusCn={statusCn} step={step} offlineAgree={onOfflineAgree}></Flow>
            
            

            {
              incomecontracts&&incomecontracts!="" &&

              <Descriptions.Item label="收款合同">
                <Filescard  urls={incomecontracts} mode='list'/>
            </Descriptions.Item>
            }
            {
              expendcontracts&&expendcontracts!="" && 
              <Descriptions.Item label="付款合同">
                <Filescard  urls={expendcontracts} mode='list'/>
            </Descriptions.Item>
            }
            {
              basic.offline==1 && basic.offlinenote &&
              <div style={{margin:'0 0 20px 20px',fontWeight:'bold'}}>{basic.offlinenote}</div>
            }
            {
              state==-1 && 
              <div>
                {
                (basic.approvalUserid||'').includes(currentUser.wxuserid) && basic.status!=FlowStateEunm.PASS  && <>
                
                  <TextArea placeholder="审批意见" autoSize={{ minRows: 2, maxRows: 4 }} value={speech} onChange={(e) => setSpeech(e.target.value)}/>
                  <Divider/>
                  </>
                }
              
                {
                !approve && basic.status==FlowStateEunm.ING  &&
                 <>
                  
                      <Button type="primary" onClick={()=>actAgree({act:'agree'})}>
                        {
                          (viewdata && viewdata.showSpecialBtn&&['预算','决算'].indexOf(basic.typename)>-1)?'同意线上会签':'同意'
                        }
                      </Button>
                      <Button type="default" onClick={() =>actReject({act:'reject'})}>
                        驳回
                      </Button>
                      {
                        ['预算','决算'].indexOf(basic.typename)>-1&&basic.offline==0&&
                        <Button type="link" onClick={()=>{
                          
                          if (viewdata && viewdata.approval){
                            if (viewdata.approval.length<=(step+1)){ // 无下个节点
                               Modal.error({'title':'禁止操作'})
                               return
                            }else{
                              
                              var node = viewdata.approval[step+1]
                              if (node.NodeAttr!=2||node.Items.Item.length<2){
                                Modal.error({title:'下个节点为会签且多人审批才能上会'})
                                return
                              }
                            }
                            
                            
                          }
                          Modal.confirm({
                            title: '确定要【线下上会】吗？',
                            content: '提交后，将进入下一流程',
                            onOk() {
                              act({act:'agree',offline:1})
                            },
                          });
                          
                        }}>
                          线下上会
                        </Button>
                      }
                  </>
                }
                {
                (basic.userId||'').includes(currentUser.wxuserid) && basic.status!=FlowStateEunm.CANCEL && <>
                
                    <Button type="primary" onClick={() => {
                      
                      act({act:'urge'})
                      }}>
                      催办
                    </Button>
                    <Button type="default" onClick={() =>actCancel({act:'cancel'})}>
                      撤销
                    </Button>
      


                    {
                      [ProjectStatesEnum.BUDGET,ProjectStatesEnum.FINAL].indexOf(basic.state)>-1&&basic.offline==1&&
                      <Button type="link" onClick={()=>{
                        setOfflineModal(true)
                        setBasic(basic)
                        
                      }}>
                        线下上会通过
                      </Button>
                    }

                </>
                
              }

              </div>
            }
            <ViewFlow onVisibleChange={setViewflowmodal} visible={viewflowmodal} thirdNo={thirdno}/>
            <Modal
              key="m1"
              title="线下上会通过"
              style={{ top: 20 }}
              width="60vw"
              visible={offlineModal}
              onOk={() => setOfflineModal(false)}
              onCancel={() => setOfflineModal(false)}
              footer={null}
            >
              <Offlineagree key={basic.id} data={basic} onChange={offlineAgree}/>
            </Modal>
            <Modal
              title=""
              style={{ top: 0,left:0, aspectRatio: '210/297'}}
              width={'60vw'}
              visible={printModal}
              onOk={() => setPrintModal(false)}
              onCancel={() => setPrintModal(false)}
              footer={null}
            >
              <Print record={basic} key={basic} typename={basic.typename}/>
            </Modal>
            <Modal
              title={null}
              style={{ top: 20 }}
              width={650}
              visible={modal2}
              onOk={() => {

              }}
              onCancel={() => setModal2(false)}
              footer={null}
            >
              
              <Filescard key={urls} urls={urls}/>
            </Modal>
        </div>
        }
    </div>
    
  )
}

export default Viewflow

// vue-project/src/views/budget/components/viewflow.vue

<template>
  <div v-if="!data.viewdata" style="margin: 10px;">暂无</div>
  <div v-if="data.viewdata" class="box1">
    <div v-if="data.basic.reject==1" class="mask">
      <div class="value" :style="{color:'red',fontWeight:'bold'}">
            <span>{{ '已驳回' }}</span>
      </div>
    </div>
     <div class="row" :style="{margin:'10px 0px'}">
        <Image width="50" radius="10" height="50" fit="cover" :round="false" :src="data.basic?.avatar"/>
        <span class="title" :style="{marginLeft:'5px',marginRight:'5px',fontWeight:'bold',color:'black!important'}">{{data.basic?.userName}}的审批申请</span>
        <Tag size="large" plain :type="tagcolor" class="head">{{data.basic?.statusname}}</Tag> 
     </div>
     <CellGroup>
      <div class="cell" v-if="data.basic?.thirdNo">
         <div class="label">审批单号：</div>
         <div class="value">{{data.basic?.thirdNo }}</div>
       </div>
      <div class="cell">
         <div class="label">申请类型：</div>
         <div class="value" >{{data.basic?.typename|| data.basic?.statename}}{{ data.basic.statename!=data.basic?.typename?(data.basic.statename?"（未"+data.basic.statename+"）":""):"" }}</div>
       </div>
       <div class="cell">
         <div class="label">项目名称：</div>
         <div class="value">{{data.basic?.title }}</div>
       </div>
       <div class="cell">
         <div class="label">项目类型：</div>
         <div class="value">{{data.basic?.protypename }}</div>
       </div>
       
       <div class="cell">
         <div class="label">申请部门：</div>
         <div class="value">{{data.basic?.department }}</div>
       </div>
       <div class="cell">
         <div class="label">项目负责人</div>
         <div class="value">{{data.basic?.chargername }}</div>
       </div>
       <div class="cell" v-if="data.basic?.submitdate&&data.basic?.typename=='提交计量'">
         <div class="label">提交月份</div>
         <div class="value">{{data.basic?.submitdate.substr(0,7) }}</div>
       </div>
       <div class="cell">
         <div class="label">总收入</div>
         <div class="value">{{income.toLocaleString('en-US', {minimumFractionDigits: 2,maximumFractionDigits: 2,}) }}</div>
       </div>
       <div class="cell">
         <div class="label">总支出</div>
         <div class="value">{{expend.toLocaleString('en-US', {minimumFractionDigits: 2,maximumFractionDigits: 2,})}}</div>
       </div>
       <div class="cell">
         <div class="label">毛利润</div>
         <div class="value">{{profit.toLocaleString('en-US', {minimumFractionDigits: 2,maximumFractionDigits: 2,}) }}</div>
       </div>
       <div class="cell">
         <div class="label">合同状态</div>
         <div class="value" :style="{color:data.basic?.contractids?'#1989fa':'black'}" @click="getContract(data.basic?.contractids)">{{data.basic?.contractids?'已签':'未签' }}</div>
       </div>
       <div class="cell" >
         <div class="label">合同回款</div>
         <div class="value">{{paycollection?paycollection.toLocaleString('en-US', {minimumFractionDigits: 2,maximumFractionDigits: 2,}):0.0}}</div>
       </div>
       <Filescard v-if="contracturls" :urls="contracturls"/>
       <div v-if="data.basic?.state<=ProjectStatesEnum.BUDGET&&data.basic?.content">
          <div class="cell" >
            <div class="label">预算备注：</div>
          </div>
          <div class="cell" >
            <div class="value">{{data.basic?.content }}</div>
          </div>
       </div>
       <div v-if="data.basic?.state>ProjectStatesEnum.BUDGET&&data.basic?.finalcontent">
          <div class="cell" >
            <div class="label">决算备注：</div>
          </div>
          <div class="cell" >
            <div class="value">{{data.basic?.finalcontent }}</div>
          </div>
       </div>

    </CellGroup>
    <div class="row title"  style="margin-top: 20px;">审批流程:</div>
    <Steps :active="step" direction="vertical" active-icon="success" active-color="#07c160">
      <Step v-for="(item,index) in data.viewdata?.approval||[]">
        <div class="row" style="padding: 0;">
          <Image width="30" height="30" fit="cover" style="margin-right: 10px;" :round="true" :src="item?.avatar"/>
          <div :style="{flexGrow:1}">
            <span v-if="item.next!='offline'&&item.offline!=1">{{item.title+(item.status&&index<=(step)?('>'+data.statusCn[item.status]):'')}}</span>
            <span v-if="item.next=='offline'">线下上会处理</span>
            <div><span v-if="(data.basic?.offline==1||item.offline==1)&&step==index"  @click="upload"  style="color: #1989fa">线下上会材料上传</span></div>
            <div><span :style="{color:'red'}">{{item.speech}}</span></div>
            
           </div>
          <div :style="{textAlign:'right',float:'right',marginRight:'10px',display:'flex',alignItems:'center'}">
            {{item.date}}
          </div>
        </div>
        <div class="row" v-if="item.next!='offline'&&item.offline!=1&& (data.basic?.offline!=1||data.basic?.offline==1&&step!=index) && item.items && item.items.length>0">
          <Badge  v-for="ele in item.items" :dot="ele.status==2">
            <Image width="25" height="25" fit="cover" style="margin-right: 2px;" :round="true" :src="ele?.avatar"/>
          </Badge>
        </div>
        <Filescard v-if="item.fileurls" :urls="item.fileurls"/>
      </Step>
    </Steps>
    <Divider/>
    <Field
      v-if="showbar"
      v-model="speech"
      rows="3"
      autosize
      label=""
      type="textarea"
      maxlength="50"
      placeholder="请输入审批意见"
      show-word-limit
    />
    <div style="height: 50px;"></div>
    <ActionBar >

      
      <!-- 审批人操作 -->
      <ActionBarButton  type="warning" :text="'上会'+typelabel" v-if="data&&data.viewdata&&data.viewdata.showSpecialBtn&&data.viewdata.offlineBtnShowBefore" @click="offline()"/>
      <ActionBarButton  type="primary" :text="(data&&data.viewdata&&data.viewdata.showSpecialBtn)?'会签'+typelabel:'同意'+typelabel " v-if="showbar&&!data.viewdata.notShowCountersign" @click="actAgree({act:'agree'})"/>
      <ActionBarButton  type="warning" :text="'上会'+typelabel" v-if="data&&data.viewdata&&data.viewdata.showSpecialBtn&&!data.viewdata.offlineBtnShowBefore" @click="offline()"/>
      <ActionBarButton type="default" text="驳回" v-if="showbar" @click="act({act:'reject'})"/>
        <!-- 经办操作 -->
      <ActionBarButton type="warning" text="上会通过" v-if="showbar2&&['预算','决算'].indexOf(data.basic?.typename)>-1&&data.basic?.offline==1" @click="upload"/>
      <ActionBarButton icon="chat-o" text="催办"  v-if="showbar2&&FlowStateEunm.PASS!=data.basic?.status" type="primary" @click="urge({act:'urge'})"/>
      <ActionBarButton icon="cross" text="撤销" color="#ff5000" v-if="showbar2&&FlowStateEunm.PASS!=data.basic?.status" type="default" @click="act({act:'cancel'})"/>
    </ActionBar>
    <Dialog v-model:show="show" title="上会材料上传" @confirm="onUploadConfirm" :show-cancel-button="true" :show-confirm-button="true">
            <Cell title="会议：">
            </Cell>
            <Field v-model="speech" rows="2" autosize label="" type="textarea" maxlength="250" placeholder="输入会议名称和日期"
                show-word-limit @focus="softKeyboard" />
            <Cell title="附件上传">
            </Cell>
            <Field name="uploader" label="">
                <template #input>
                    <Uploader  v-model="uploadImage"  multiple :max-count="10" accept="image/*,.pdf" :before-read="beforeRead"
                        :after-read="afterRead" :before-delete="beforeDelete" />
                </template>
            </Field>
           
    </Dialog>

  </div>
</template>
<script  lang="ts">

import { Divider, Image,Tag,Cell,CellGroup,Steps,Step,Badge,Field,Button,showDialog,showConfirmDialog,Dialog,Uploader,ActionBar,ActionBarIcon,ActionBarButton} from 'vant';
import { flowact, getflowdata,getfileurlsbycontractids } from '../budget';
import Filescard from './filescard.vue'
import { ProjectStatesEnum,FlowStateEunm } from '../config';
import { useUserStore } from '@/stores';
import { storeToRefs } from 'pinia';
import { checkUploadType, uploadedFiles, previewImage,softKeyboard } from '../../../utils/common'
import { uploadDelete } from '../../../api/config'
import { setToUrl } from '../utils';
import { ref } from 'vue';
const { loginStatus, userInfo } = storeToRefs(useUserStore());

export default {
  components: {
    Image,Tag,Divider,Cell,CellGroup,Steps,Step,Badge,Filescard,Field,Button,Dialog,Uploader,ActionBar,ActionBarIcon,ActionBarButton 
  },
  props: ['thirdNo', 'projectid','state','paycollection'],
  data () {
    return {
      active:0,
      data:<any>{},
      step:0,
      speech:'',
      userid:'',
      ProjectStatesEnum:ProjectStatesEnum,
      FlowStateEunm:FlowStateEunm,
      showbar:false,
      showbar2:false,
      show:false,
      files:<any>[],
      uploadImage:<any>[],
      softKeyboard:softKeyboard,
      showContract:false,
      contracturls:'',
      statecolor:['default','primary','success','default','default'],
      tagcolor:<any>'default',
      income:0,
      expend:0,
      profit:0,
      typelabel:'',
      reset:false,
    }
  },
  mounted() {
   
   this.userid = userInfo.value.userId

  },
  created() {
    this.getdata()
  },
  methods:{
    upload(){
      this.show = true
    },
    onUploadChange(e:any){
      console.log(e)
    },
    onUploadConfirm(){
      var fileurls = this.files.map((u:any)=>{
        return setToUrl(u)
      }).join(',')
      if (!this.speech) {
        showDialog({message:'请输入会议名称和日期'})
        return
      }
      var flow:any = {fileurls}
      flow.act='offlineAgree'
      flow.offline=0
      this.act(flow)
    },
    beforeRead(file: any){
      return true
    },
    afterRead(file: any) {
        console.log('afterread')
        uploadedFiles(file, { 'uploadType': "3", 'uploadPath': 'contract' },(e:any)=>{
          this.files.push(...e)
        })
        
    },
    beforeDelete  (file: any) {
        uploadDelete(file._url).then((res:any)=>{
          if(res.success){
            this.files.splice(this.files.findIndex((item:any)=>item.url==file._url),1)
          }
        })
        return true
    },
    getdata(){
      var par:any = {projectid:this.projectid}
      if (this.state) par.state = this.state
      if (this.thirdNo) par.thirdNo = this.thirdNo
      getflowdata(par).then((res:any)=>{
      
      this.data = res
      if(['预算','决算'].indexOf(res.basic?.typename)>-1){

        this.typelabel = '（'+this.data.basic?.typename+'）'
      }
      this.showbar = (this.data.basic?.approvalUserid||'').indexOf(this.userid)>-1 && this.data.basic?.status==FlowStateEunm.ING
      this.showbar2=(this.data.basic?.userId||'').indexOf(this.userid)>-1 && this.data.basic?.status!=FlowStateEunm.CANCEL
      if(res && res.basic){
        this.tagcolor = this.statecolor[res.basic?.status] || 'default'
      }
      
      // 计算总收入、总支出和总毛利
      var income = 0
      var expend = 0
      var profit = 0
      if (res.basic.finalincome>0){
        income = res.basic.finalincome
        expend = res.basic.realfinalexpend
      }else{
        income = res.basic.budgetincome
        expend = res.basic.realbudgetexpend
      }
      profit = income-expend
      profit = profit>0?profit:0
      this.income = income
      this.expend = expend
      this.profit = profit
      
      if (res.viewdata) {
          this.step=res.viewdata.step+1
          const items = res.viewdata.approval[this.step].Items.Item
          for (var i=0;i<items.length;i++){
            if (items[i].ItemStatus==2 && items[i].ItemUserId==this.userid){
              this.showbar = false
              break
            }
          }

        
        }
        if(res.basic?.offline) this.showbar=false
      })
    },
    urge(flow:any){
      if (!flow.thirdNo) flow.thirdNo = this.data.basic?.thirdNo||this.data.basic?.thirdno
      flowact(flow).then((res:any)=>{
        if (res.errorMessage){
        }else{
          showDialog({'message':'催办成功'})
        }
      })
    },
    actAgree(flow:any){
      showConfirmDialog({
        title: '确定同意【'+this.data.basic?.typename+'】吗？'
      })
        .then(() => {
          this.act(flow)
        })
        .catch(() => {
          // on cancel
        });
    },
    act(flow:any){
      if (!flow.thirdNo) flow.thirdNo = this.data.basic?.thirdNo||this.data.basic?.thirdno
      if (!flow.speech) flow.speech= this.speech

      flowact(flow).then((flowres:any)=>{
        if (flowres.errorMessage){
          this.getdata()
        }else{
          if (flowres.data && flowres.data.touser&&flowres.data.touser.indexOf(this.userid)>-1){
            var node = this.data.viewdata.approval[this.step]
            if (node.NodeAttr==2&&node.Items.Item.length>1){
              console.log('当前节点为会签节点且有多人审批，禁止自动连审！')
              this.getdata()
              return
            }
            
            flow.continuous = 1
            this.act(flow)
          }else{
            
            this.getdata()
          }
        }
      })
        
    },
    continue(){
      Dialog.confirm({
        title: '确定要提交审批吗？',
        onOk() {
          this.act({act:'continue'})
        },
      });
    },
    offline(){
      var viewdata = this.data.viewdata
      if (viewdata && viewdata.approval){
            if (viewdata.approval.length<=(this.step+1)){ // 无下个节点
                showDialog({'message':'禁止操作'})
                return
            }else{
              
              var node = viewdata.approval[this.step+1]
              if (node.NodeAttr!=2||node.Items.Item.length<2){
                showDialog({message:'下个节点为会签且多人审批才能上会'})
                return
              }
            }
            
            
          }
          showConfirmDialog({
            title: '确定要【线下上会】吗？'
          })
            .then(() => {
              this.act({act:'agree',offline:1})
            })
            .catch(() => {
              // on cancel
            });

    },
    getContract(ids:any){
      if (ids){
        getfileurlsbycontractids({contractids:ids}).then(res=>{
          if (res){
            this.contracturls = res.data
            this.showContract = true
          }
        })
      }
    }
  }
}
</script>
<style   lang="css">
  .mask{
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: linear-gradient(to bottom, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.5));
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 9999;
    color: white;
    font-size: 20px;
    font-weight: bold;
    
  }
  .title{
    font-weight: bold;
    font-size: calc(var(--van-cell-font-size)*var(--Big));
  }
  span{
    font-size: 14px;
  }
  .box1{
    width: 100%;
    min-height: 100vh;
  }
  .row{
    /* width: 100%; */
    display: flex;
    flex-direction: row;
    align-items: center;
    padding: 2px 10px;
  }
  .row .label{
    flex: none;
    box-sizing: border-box;
    width: calc(var(--van-field-label-width)*0.9);
    color: #969799;
    text-align: left;
    word-wrap: break-word;
  }
  .row .value{
    position: relative;
    overflow: hidden;
    color: #323233;
    text-align: left;
    vertical-align: middle;
    word-wrap: break-word;
  }
  .cell{
    position: relative;
    display: flex;
    box-sizing: border-box;
    width: 100%;
    padding: 8px var(--van-cell-horizontal-padding) 0 var(--van-cell-horizontal-padding);
    overflow: hidden;
    color: var(--van-cell-text-color);
    font-size: calc(var(--van-cell-font-size)*var(--Big));
    line-height: var(--van-cell-line-height);
    background: var(--van-cell-background);
    flex-wrap: wrap;
    
   
  }
  .cell::after {
    content: '';
    display: block;
    width: 100%;
    margin: 0 auto;
    margin-top: 8px;
    border-bottom: 1px solid rgb(249, 247, 247);
  }
  .cell .label{
    flex: none;
    box-sizing: border-box;
    width: calc(var(--van-field-label-width)*0.9);
    color: #969799;
    text-align: left;
    word-wrap: break-word;
  }
  .cell .value{
    position: relative;
    overflow: hidden;
    color: #323233;
    text-align: left;
    vertical-align: middle;
    word-wrap: break-word;
  }
  .van-cell .van-cell__title span{
    font-size: calc(var(--van-cell-font-size)*0.8*var(--Big))!important;
  }

 
</style>
<style>
  @media screen and (min-width: 500px) {
    .title{
      font-weight: bold;
      font-size: 18px;
    }
    span{
      font-size: 18px;
    }
    .box1{
      width: 100%;
      min-height: 100vh;
    }
    .row{
      /* width: 100%; */
      display: flex;
      flex-direction: row;
      align-items: center;
      padding: 2px 10px;
    }
    .row .label{
      color: rgb(160, 157, 157);
      width: 100px;
      font-size: 16px;
    }
    .row .value{
      font-size: 20px;
    }
    .van-action-bar {
        position: relative;
        /* right: 0;
        bottom: 0;
        left: 0;  */
        display: flex;
        flex-direction: row;
        align-items: center;
        box-sizing: content-box;
        height: var(--van-action-bar-height);
        background: var(--van-action-bar-background);
        max-width: 500px;
        justify-content: center;
    }
      
  }
</style>
